name: Test

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Download as6809 and aslink
        run: |
          sudo curl -L https://github.com/pblop/asxxxx/releases/download/5p10/as6809-linux-amd64 -o /usr/bin/as6809
          sudo curl -L https://github.com/pblop/asxxxx/releases/download/5p10/aslink-linux-amd64 -o /usr/bin/aslink
          sudo curl -L https://github.com/pblop/exec09/releases/download/json_mem_dumps/m6809-run-linux-amd64 -o /usr/bin/m6809-run
          sudo chmod +x /usr/bin/as6809 /usr/bin/aslink /usr/bin/m6809-run
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build programs
        run: bun run build-test-programs
      - run: |
          bun test --timeout 5000
        env:
          FORCE_COLOR: 3
